import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smart Catalogue Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} font-sans antialiased bg-gray-50 text-gray-900`}
        suppressHydrationWarning
      >
        <ClerkProvider
          appearance={{
            variables: {
              colorPrimary: "#4f46e5",
              colorText: "#1e293b",
              borderRadius: "0.5rem",
            },
            elements: {
              card: "rounded-lg shadow-lg border border-gray-100 bg-white",
              headerTitle: "text-xl font-semibold tracking-tight",
              headerSubtitle: "text-sm text-slate-500",
              formFieldInput:
                "rounded-md border border-gray-200 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500",
              formButtonPrimary:
                "rounded-md h-10 text-sm font-medium bg-indigo-600 hover:bg-indigo-700",
              footer: "hidden",
            },
          }}
        >
          {children}
        </ClerkProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}